/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddRoomMember,
  CreateRoom,
  GetMessage,
  HTTPValidationError,
  ResponseSchema,
  RoomBase,
  SubmitMessage,
  UpdateMessage,
  UserResponse,
} from '../models/index';
import {
    AddRoomMemberFromJSON,
    AddRoomMemberToJSON,
    CreateRoomFromJSON,
    CreateRoomToJSON,
    GetMessageFromJSON,
    GetMessageToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ResponseSchemaFromJSON,
    ResponseSchemaToJSON,
    RoomBaseFromJSON,
    RoomBaseToJSON,
    SubmitMessageFromJSON,
    SubmitMessageToJSON,
    UpdateMessageFromJSON,
    UpdateMessageToJSON,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/index';

export interface AddRoomMemberTalkAddRoomMemberPostRequest {
    addRoomMember: AddRoomMember;
}

export interface CreateRoomTalkCreateRoomPostRequest {
    createRoom: CreateRoom;
}

export interface DeleteMessageTalkMessageDeleteMessageIdDeleteRequest {
    messageId: number;
}

export interface ReadRoomTalkFriendInformationRoomIdGetRequest {
    roomId: number;
}

export interface ReadRoomTalkUserInformationRoomIdGetRequest {
    roomId: number;
}

export interface SearchRoomTalkSearchMakeUsersRoomPostRequest {
    user1Id: number;
    user2Id: number;
}

export interface SubmitMessageTalkMessageSubmitPostRequest {
    submitMessage: SubmitMessage;
}

export interface UpdateTalkMessageUpdatePutRequest {
    updateMessage: UpdateMessage;
}

/**
 * 
 */
export class DMApi extends runtime.BaseAPI {

    /**
     * Creates request options for addRoomMemberTalkAddRoomMemberPost without sending the request
     */
    async addRoomMemberTalkAddRoomMemberPostRequestOpts(requestParameters: AddRoomMemberTalkAddRoomMemberPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['addRoomMember'] == null) {
            throw new runtime.RequiredError(
                'addRoomMember',
                'Required parameter "addRoomMember" was null or undefined when calling addRoomMemberTalkAddRoomMemberPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/add_room_member`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddRoomMemberToJSON(requestParameters['addRoomMember']),
        };
    }

    /**
     * Add Room Member
     */
    async addRoomMemberTalkAddRoomMemberPostRaw(requestParameters: AddRoomMemberTalkAddRoomMemberPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.addRoomMemberTalkAddRoomMemberPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Add Room Member
     */
    async addRoomMemberTalkAddRoomMemberPost(requestParameters: AddRoomMemberTalkAddRoomMemberPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.addRoomMemberTalkAddRoomMemberPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createRoomTalkCreateRoomPost without sending the request
     */
    async createRoomTalkCreateRoomPostRequestOpts(requestParameters: CreateRoomTalkCreateRoomPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createRoom'] == null) {
            throw new runtime.RequiredError(
                'createRoom',
                'Required parameter "createRoom" was null or undefined when calling createRoomTalkCreateRoomPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/create_room`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoomToJSON(requestParameters['createRoom']),
        };
    }

    /**
     * Create Room
     */
    async createRoomTalkCreateRoomPostRaw(requestParameters: CreateRoomTalkCreateRoomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.createRoomTalkCreateRoomPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Create Room
     */
    async createRoomTalkCreateRoomPost(requestParameters: CreateRoomTalkCreateRoomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.createRoomTalkCreateRoomPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteMessageTalkMessageDeleteMessageIdDelete without sending the request
     */
    async deleteMessageTalkMessageDeleteMessageIdDeleteRequestOpts(requestParameters: DeleteMessageTalkMessageDeleteMessageIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling deleteMessageTalkMessageDeleteMessageIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/message_delete/{message_id}`;
        urlPath = urlPath.replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Message
     */
    async deleteMessageTalkMessageDeleteMessageIdDeleteRaw(requestParameters: DeleteMessageTalkMessageDeleteMessageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.deleteMessageTalkMessageDeleteMessageIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Delete Message
     */
    async deleteMessageTalkMessageDeleteMessageIdDelete(requestParameters: DeleteMessageTalkMessageDeleteMessageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.deleteMessageTalkMessageDeleteMessageIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRoomsByUserTalkUserRoomsGet without sending the request
     */
    async getRoomsByUserTalkUserRoomsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/user_rooms`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Rooms By User
     */
    async getRoomsByUserTalkUserRoomsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoomBase>>> {
        const requestOptions = await this.getRoomsByUserTalkUserRoomsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoomBaseFromJSON));
    }

    /**
     * Get Rooms By User
     */
    async getRoomsByUserTalkUserRoomsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoomBase>> {
        const response = await this.getRoomsByUserTalkUserRoomsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readRoomTalkFriendInformationRoomIdGet without sending the request
     */
    async readRoomTalkFriendInformationRoomIdGetRequestOpts(requestParameters: ReadRoomTalkFriendInformationRoomIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling readRoomTalkFriendInformationRoomIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/friend_information/{room_id}`;
        urlPath = urlPath.replace(`{${"room_id"}}`, encodeURIComponent(String(requestParameters['roomId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read Room
     */
    async readRoomTalkFriendInformationRoomIdGetRaw(requestParameters: ReadRoomTalkFriendInformationRoomIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.readRoomTalkFriendInformationRoomIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Read Room
     */
    async readRoomTalkFriendInformationRoomIdGet(requestParameters: ReadRoomTalkFriendInformationRoomIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.readRoomTalkFriendInformationRoomIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readRoomTalkUserInformationRoomIdGet without sending the request
     */
    async readRoomTalkUserInformationRoomIdGetRequestOpts(requestParameters: ReadRoomTalkUserInformationRoomIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['roomId'] == null) {
            throw new runtime.RequiredError(
                'roomId',
                'Required parameter "roomId" was null or undefined when calling readRoomTalkUserInformationRoomIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/user_information/{room_id}`;
        urlPath = urlPath.replace(`{${"room_id"}}`, encodeURIComponent(String(requestParameters['roomId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read Room
     */
    async readRoomTalkUserInformationRoomIdGetRaw(requestParameters: ReadRoomTalkUserInformationRoomIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetMessage>>> {
        const requestOptions = await this.readRoomTalkUserInformationRoomIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetMessageFromJSON));
    }

    /**
     * Read Room
     */
    async readRoomTalkUserInformationRoomIdGet(requestParameters: ReadRoomTalkUserInformationRoomIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetMessage>> {
        const response = await this.readRoomTalkUserInformationRoomIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchRoomTalkSearchMakeUsersRoomPost without sending the request
     */
    async searchRoomTalkSearchMakeUsersRoomPostRequestOpts(requestParameters: SearchRoomTalkSearchMakeUsersRoomPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['user1Id'] == null) {
            throw new runtime.RequiredError(
                'user1Id',
                'Required parameter "user1Id" was null or undefined when calling searchRoomTalkSearchMakeUsersRoomPost().'
            );
        }

        if (requestParameters['user2Id'] == null) {
            throw new runtime.RequiredError(
                'user2Id',
                'Required parameter "user2Id" was null or undefined when calling searchRoomTalkSearchMakeUsersRoomPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['user1Id'] != null) {
            queryParameters['user1_id'] = requestParameters['user1Id'];
        }

        if (requestParameters['user2Id'] != null) {
            queryParameters['user2_id'] = requestParameters['user2Id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/search_make_users_room`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search Room
     */
    async searchRoomTalkSearchMakeUsersRoomPostRaw(requestParameters: SearchRoomTalkSearchMakeUsersRoomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomBase>> {
        const requestOptions = await this.searchRoomTalkSearchMakeUsersRoomPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomBaseFromJSON(jsonValue));
    }

    /**
     * Search Room
     */
    async searchRoomTalkSearchMakeUsersRoomPost(requestParameters: SearchRoomTalkSearchMakeUsersRoomPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomBase> {
        const response = await this.searchRoomTalkSearchMakeUsersRoomPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for submitMessageTalkMessageSubmitPost without sending the request
     */
    async submitMessageTalkMessageSubmitPostRequestOpts(requestParameters: SubmitMessageTalkMessageSubmitPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['submitMessage'] == null) {
            throw new runtime.RequiredError(
                'submitMessage',
                'Required parameter "submitMessage" was null or undefined when calling submitMessageTalkMessageSubmitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/message_submit`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitMessageToJSON(requestParameters['submitMessage']),
        };
    }

    /**
     * Submit Message
     */
    async submitMessageTalkMessageSubmitPostRaw(requestParameters: SubmitMessageTalkMessageSubmitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.submitMessageTalkMessageSubmitPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Submit Message
     */
    async submitMessageTalkMessageSubmitPost(requestParameters: SubmitMessageTalkMessageSubmitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.submitMessageTalkMessageSubmitPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateTalkMessageUpdatePut without sending the request
     */
    async updateTalkMessageUpdatePutRequestOpts(requestParameters: UpdateTalkMessageUpdatePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateMessage'] == null) {
            throw new runtime.RequiredError(
                'updateMessage',
                'Required parameter "updateMessage" was null or undefined when calling updateTalkMessageUpdatePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/talk/message_update`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMessageToJSON(requestParameters['updateMessage']),
        };
    }

    /**
     * Update
     */
    async updateTalkMessageUpdatePutRaw(requestParameters: UpdateTalkMessageUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.updateTalkMessageUpdatePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Update
     */
    async updateTalkMessageUpdatePut(requestParameters: UpdateTalkMessageUpdatePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.updateTalkMessageUpdatePutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
