/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface GetEmotionByMessageEmotionGetEmotionByMessagePostRequest {
    messageId: number;
}

export interface GetEmotionByPostEmotionGetEmotionByPostPostRequest {
    postId: number;
}

/**
 * 
 */
export class EmotionApi extends runtime.BaseAPI {

    /**
     * Creates request options for getEmotionByMessageEmotionGetEmotionByMessagePost without sending the request
     */
    async getEmotionByMessageEmotionGetEmotionByMessagePostRequestOpts(requestParameters: GetEmotionByMessageEmotionGetEmotionByMessagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling getEmotionByMessageEmotionGetEmotionByMessagePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['messageId'] != null) {
            queryParameters['message_id'] = requestParameters['messageId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/emotion/get_emotion_by_message`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Emotion By Message
     */
    async getEmotionByMessageEmotionGetEmotionByMessagePostRaw(requestParameters: GetEmotionByMessageEmotionGetEmotionByMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.getEmotionByMessageEmotionGetEmotionByMessagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Emotion By Message
     */
    async getEmotionByMessageEmotionGetEmotionByMessagePost(requestParameters: GetEmotionByMessageEmotionGetEmotionByMessagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getEmotionByMessageEmotionGetEmotionByMessagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getEmotionByPostEmotionGetEmotionByPostPost without sending the request
     */
    async getEmotionByPostEmotionGetEmotionByPostPostRequestOpts(requestParameters: GetEmotionByPostEmotionGetEmotionByPostPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getEmotionByPostEmotionGetEmotionByPostPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['postId'] != null) {
            queryParameters['post_id'] = requestParameters['postId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/emotion/get_emotion_by_post`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Emotion By Post
     */
    async getEmotionByPostEmotionGetEmotionByPostPostRaw(requestParameters: GetEmotionByPostEmotionGetEmotionByPostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.getEmotionByPostEmotionGetEmotionByPostPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Emotion By Post
     */
    async getEmotionByPostEmotionGetEmotionByPostPost(requestParameters: GetEmotionByPostEmotionGetEmotionByPostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getEmotionByPostEmotionGetEmotionByPostPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
