/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface FakeCheckByPostFakecheckFakeCheckByPostPostRequest {
    postId: number;
}

/**
 * 
 */
export class FakecheckApi extends runtime.BaseAPI {

    /**
     * Creates request options for fakeCheckByPostFakecheckFakeCheckByPostPost without sending the request
     */
    async fakeCheckByPostFakecheckFakeCheckByPostPostRequestOpts(requestParameters: FakeCheckByPostFakecheckFakeCheckByPostPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling fakeCheckByPostFakecheckFakeCheckByPostPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['postId'] != null) {
            queryParameters['post_id'] = requestParameters['postId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/fakecheck/fake_check_by_post`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fake Check By Post
     */
    async fakeCheckByPostFakecheckFakeCheckByPostPostRaw(requestParameters: FakeCheckByPostFakecheckFakeCheckByPostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.fakeCheckByPostFakecheckFakeCheckByPostPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Fake Check By Post
     */
    async fakeCheckByPostFakecheckFakeCheckByPostPost(requestParameters: FakeCheckByPostFakecheckFakeCheckByPostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.fakeCheckByPostFakecheckFakeCheckByPostPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
