/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ResponseSchema,
  UserResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ResponseSchemaFromJSON,
    ResponseSchemaToJSON,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/index';

export interface CreateFriendsFriendsMakeFriendsPostRequest {
    userId: number;
    friendsId: number;
}

export interface DeleteFriendsFriendsDeleteFriendsDeleteRequest {
    userId: number;
    friendsId: number;
}

export interface GetFriendsListFriendsFriendsListUserIdGetRequest {
    userId: number;
}

/**
 * 
 */
export class FriendsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createFriendsFriendsMakeFriendsPost without sending the request
     */
    async createFriendsFriendsMakeFriendsPostRequestOpts(requestParameters: CreateFriendsFriendsMakeFriendsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling createFriendsFriendsMakeFriendsPost().'
            );
        }

        if (requestParameters['friendsId'] == null) {
            throw new runtime.RequiredError(
                'friendsId',
                'Required parameter "friendsId" was null or undefined when calling createFriendsFriendsMakeFriendsPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['friendsId'] != null) {
            queryParameters['friends_id'] = requestParameters['friendsId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/friends/make_friends`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Create Friends
     */
    async createFriendsFriendsMakeFriendsPostRaw(requestParameters: CreateFriendsFriendsMakeFriendsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.createFriendsFriendsMakeFriendsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Create Friends
     */
    async createFriendsFriendsMakeFriendsPost(requestParameters: CreateFriendsFriendsMakeFriendsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.createFriendsFriendsMakeFriendsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteFriendsFriendsDeleteFriendsDelete without sending the request
     */
    async deleteFriendsFriendsDeleteFriendsDeleteRequestOpts(requestParameters: DeleteFriendsFriendsDeleteFriendsDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteFriendsFriendsDeleteFriendsDelete().'
            );
        }

        if (requestParameters['friendsId'] == null) {
            throw new runtime.RequiredError(
                'friendsId',
                'Required parameter "friendsId" was null or undefined when calling deleteFriendsFriendsDeleteFriendsDelete().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['friendsId'] != null) {
            queryParameters['friends_id'] = requestParameters['friendsId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/friends/delete_friends`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Friends
     */
    async deleteFriendsFriendsDeleteFriendsDeleteRaw(requestParameters: DeleteFriendsFriendsDeleteFriendsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.deleteFriendsFriendsDeleteFriendsDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Delete Friends
     */
    async deleteFriendsFriendsDeleteFriendsDelete(requestParameters: DeleteFriendsFriendsDeleteFriendsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.deleteFriendsFriendsDeleteFriendsDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getFriendsListFriendsFriendsListUserIdGet without sending the request
     */
    async getFriendsListFriendsFriendsListUserIdGetRequestOpts(requestParameters: GetFriendsListFriendsFriendsListUserIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling getFriendsListFriendsFriendsListUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/friends/friends_list/{user_id}`;
        urlPath = urlPath.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Friends List
     */
    async getFriendsListFriendsFriendsListUserIdGetRaw(requestParameters: GetFriendsListFriendsFriendsListUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UserResponse>>> {
        const requestOptions = await this.getFriendsListFriendsFriendsListUserIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserResponseFromJSON));
    }

    /**
     * Get Friends List
     */
    async getFriendsListFriendsFriendsListUserIdGet(requestParameters: GetFriendsListFriendsFriendsListUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserResponse>> {
        const response = await this.getFriendsListFriendsFriendsListUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
