/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyCreatePostWithImageTweetcreatePostWithImagePost,
  CreatePostModel,
  GetReplyPostModel,
  HTTPValidationError,
  PostImage,
  PostModel,
  ReplyModel,
  ResponseSchema,
} from '../models/index';
import {
    BodyCreatePostWithImageTweetcreatePostWithImagePostFromJSON,
    BodyCreatePostWithImageTweetcreatePostWithImagePostToJSON,
    CreatePostModelFromJSON,
    CreatePostModelToJSON,
    GetReplyPostModelFromJSON,
    GetReplyPostModelToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PostImageFromJSON,
    PostImageToJSON,
    PostModelFromJSON,
    PostModelToJSON,
    ReplyModelFromJSON,
    ReplyModelToJSON,
    ResponseSchemaFromJSON,
    ResponseSchemaToJSON,
} from '../models/index';

export interface CreatePostTweetcreatePostPostRequest {
    createPostModel: CreatePostModel;
}

export interface CreatePostWithImageTweetcreatePostWithImagePostRequest {
    bodyCreatePostWithImageTweetcreatePostWithImagePost: BodyCreatePostWithImageTweetcreatePostWithImagePost;
}

export interface DeletePostTweetdeletePostPostIdDeleteRequest {
    postId: number;
}

export interface GetGoodNumTweetpostsGoodNumPostIdGetRequest {
    postId: number;
}

export interface GetImagesTweetpostsImagesPostIdGetRequest {
    postId: number;
}

export interface GetReplysTweetpostsReplyPostIdGetRequest {
    postId: number;
}

export interface PostLikeTweetmanegeLikePostIdPostRequest {
    postId: number;
}

export interface UpdatePostTweetupdatePostPutRequest {
    postModel: PostModel;
}

/**
 * 
 */
export class TweetApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPostTweetcreatePostPost without sending the request
     */
    async createPostTweetcreatePostPostRequestOpts(requestParameters: CreatePostTweetcreatePostPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createPostModel'] == null) {
            throw new runtime.RequiredError(
                'createPostModel',
                'Required parameter "createPostModel" was null or undefined when calling createPostTweetcreatePostPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/create_post`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePostModelToJSON(requestParameters['createPostModel']),
        };
    }

    /**
     * Create Post
     */
    async createPostTweetcreatePostPostRaw(requestParameters: CreatePostTweetcreatePostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.createPostTweetcreatePostPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Create Post
     */
    async createPostTweetcreatePostPost(requestParameters: CreatePostTweetcreatePostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.createPostTweetcreatePostPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPostWithImageTweetcreatePostWithImagePost without sending the request
     */
    async createPostWithImageTweetcreatePostWithImagePostRequestOpts(requestParameters: CreatePostWithImageTweetcreatePostWithImagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bodyCreatePostWithImageTweetcreatePostWithImagePost'] == null) {
            throw new runtime.RequiredError(
                'bodyCreatePostWithImageTweetcreatePostWithImagePost',
                'Required parameter "bodyCreatePostWithImageTweetcreatePostWithImagePost" was null or undefined when calling createPostWithImageTweetcreatePostWithImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/create_post_with_image`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyCreatePostWithImageTweetcreatePostWithImagePostToJSON(requestParameters['bodyCreatePostWithImageTweetcreatePostWithImagePost']),
        };
    }

    /**
     * Create Post With Image
     */
    async createPostWithImageTweetcreatePostWithImagePostRaw(requestParameters: CreatePostWithImageTweetcreatePostWithImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.createPostWithImageTweetcreatePostWithImagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Create Post With Image
     */
    async createPostWithImageTweetcreatePostWithImagePost(requestParameters: CreatePostWithImageTweetcreatePostWithImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.createPostWithImageTweetcreatePostWithImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePostTweetdeletePostPostIdDelete without sending the request
     */
    async deletePostTweetdeletePostPostIdDeleteRequestOpts(requestParameters: DeletePostTweetdeletePostPostIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling deletePostTweetdeletePostPostIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/delete_post/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Post
     */
    async deletePostTweetdeletePostPostIdDeleteRaw(requestParameters: DeletePostTweetdeletePostPostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.deletePostTweetdeletePostPostIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Delete Post
     */
    async deletePostTweetdeletePostPostIdDelete(requestParameters: DeletePostTweetdeletePostPostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.deletePostTweetdeletePostPostIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGoodNumTweetpostsGoodNumPostIdGet without sending the request
     */
    async getGoodNumTweetpostsGoodNumPostIdGetRequestOpts(requestParameters: GetGoodNumTweetpostsGoodNumPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getGoodNumTweetpostsGoodNumPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts/good_num/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Good Num
     */
    async getGoodNumTweetpostsGoodNumPostIdGetRaw(requestParameters: GetGoodNumTweetpostsGoodNumPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.getGoodNumTweetpostsGoodNumPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Good Num
     */
    async getGoodNumTweetpostsGoodNumPostIdGet(requestParameters: GetGoodNumTweetpostsGoodNumPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getGoodNumTweetpostsGoodNumPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getImagesTweetpostsImagesPostIdGet without sending the request
     */
    async getImagesTweetpostsImagesPostIdGetRequestOpts(requestParameters: GetImagesTweetpostsImagesPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getImagesTweetpostsImagesPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts/images/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Images
     */
    async getImagesTweetpostsImagesPostIdGetRaw(requestParameters: GetImagesTweetpostsImagesPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PostImage>>> {
        const requestOptions = await this.getImagesTweetpostsImagesPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PostImageFromJSON));
    }

    /**
     * Get Images
     */
    async getImagesTweetpostsImagesPostIdGet(requestParameters: GetImagesTweetpostsImagesPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PostImage>> {
        const response = await this.getImagesTweetpostsImagesPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPostsTweetPostsGet without sending the request
     */
    async getPostsTweetPostsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Posts
     */
    async getPostsTweetPostsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetReplyPostModel>>> {
        const requestOptions = await this.getPostsTweetPostsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetReplyPostModelFromJSON));
    }

    /**
     * Get Posts
     */
    async getPostsTweetPostsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetReplyPostModel>> {
        const response = await this.getPostsTweetPostsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReplysTweetpostsReplyPostIdGet without sending the request
     */
    async getReplysTweetpostsReplyPostIdGetRequestOpts(requestParameters: GetReplysTweetpostsReplyPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getReplysTweetpostsReplyPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts/reply/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Replys
     */
    async getReplysTweetpostsReplyPostIdGetRaw(requestParameters: GetReplysTweetpostsReplyPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReplyModel>>> {
        const requestOptions = await this.getReplysTweetpostsReplyPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReplyModelFromJSON));
    }

    /**
     * Get Replys
     */
    async getReplysTweetpostsReplyPostIdGet(requestParameters: GetReplysTweetpostsReplyPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReplyModel>> {
        const response = await this.getReplysTweetpostsReplyPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postLikeTweetmanegeLikePostIdPost without sending the request
     */
    async postLikeTweetmanegeLikePostIdPostRequestOpts(requestParameters: PostLikeTweetmanegeLikePostIdPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postLikeTweetmanegeLikePostIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/manege_like/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Post Like
     */
    async postLikeTweetmanegeLikePostIdPostRaw(requestParameters: PostLikeTweetmanegeLikePostIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.postLikeTweetmanegeLikePostIdPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Post Like
     */
    async postLikeTweetmanegeLikePostIdPost(requestParameters: PostLikeTweetmanegeLikePostIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.postLikeTweetmanegeLikePostIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePostTweetupdatePostPut without sending the request
     */
    async updatePostTweetupdatePostPutRequestOpts(requestParameters: UpdatePostTweetupdatePostPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postModel'] == null) {
            throw new runtime.RequiredError(
                'postModel',
                'Required parameter "postModel" was null or undefined when calling updatePostTweetupdatePostPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/update_post`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PostModelToJSON(requestParameters['postModel']),
        };
    }

    /**
     * Update Post
     */
    async updatePostTweetupdatePostPutRaw(requestParameters: UpdatePostTweetupdatePostPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.updatePostTweetupdatePostPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Update Post
     */
    async updatePostTweetupdatePostPut(requestParameters: UpdatePostTweetupdatePostPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.updatePostTweetupdatePostPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
