/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BodyCreatePostWithImageTweetCreatePostWithImagePost,
  CreatePostModel,
  GetReplyPostModel,
  HTTPValidationError,
  PostImage,
  PostModel,
  ReplyModel,
  ResponseSchema,
} from '../models/index';
import {
    BodyCreatePostWithImageTweetCreatePostWithImagePostFromJSON,
    BodyCreatePostWithImageTweetCreatePostWithImagePostToJSON,
    CreatePostModelFromJSON,
    CreatePostModelToJSON,
    GetReplyPostModelFromJSON,
    GetReplyPostModelToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PostImageFromJSON,
    PostImageToJSON,
    PostModelFromJSON,
    PostModelToJSON,
    ReplyModelFromJSON,
    ReplyModelToJSON,
    ResponseSchemaFromJSON,
    ResponseSchemaToJSON,
} from '../models/index';

export interface CreatePostTweetCreatePostPostRequest {
    createPostModel: CreatePostModel;
}

export interface CreatePostWithImageTweetCreatePostWithImagePostRequest {
    bodyCreatePostWithImageTweetCreatePostWithImagePost: BodyCreatePostWithImageTweetCreatePostWithImagePost;
}

export interface DeletePostTweetDeletePostPostIdDeleteRequest {
    postId: number;
}

export interface GetGoodNumTweetPostsGoodNumPostIdGetRequest {
    postId: number;
}

export interface GetImagesTweetPostsImagesPostIdGetRequest {
    postId: number;
}

export interface GetReplysTweetPostsReplyPostIdGetRequest {
    postId: number;
}

export interface PostLikeTweetManegeLikePostIdPostRequest {
    postId: number;
}

export interface UpdatePostTweetUpdatePostPutRequest {
    postModel: PostModel;
}

/**
 * 
 */
export class TweetApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPostTweetCreatePostPost without sending the request
     */
    async createPostTweetCreatePostPostRequestOpts(requestParameters: CreatePostTweetCreatePostPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createPostModel'] == null) {
            throw new runtime.RequiredError(
                'createPostModel',
                'Required parameter "createPostModel" was null or undefined when calling createPostTweetCreatePostPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/create_post`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePostModelToJSON(requestParameters['createPostModel']),
        };
    }

    /**
     * Create Post
     */
    async createPostTweetCreatePostPostRaw(requestParameters: CreatePostTweetCreatePostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.createPostTweetCreatePostPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Create Post
     */
    async createPostTweetCreatePostPost(requestParameters: CreatePostTweetCreatePostPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.createPostTweetCreatePostPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createPostWithImageTweetCreatePostWithImagePost without sending the request
     */
    async createPostWithImageTweetCreatePostWithImagePostRequestOpts(requestParameters: CreatePostWithImageTweetCreatePostWithImagePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bodyCreatePostWithImageTweetCreatePostWithImagePost'] == null) {
            throw new runtime.RequiredError(
                'bodyCreatePostWithImageTweetCreatePostWithImagePost',
                'Required parameter "bodyCreatePostWithImageTweetCreatePostWithImagePost" was null or undefined when calling createPostWithImageTweetCreatePostWithImagePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/create_post_with_image`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyCreatePostWithImageTweetCreatePostWithImagePostToJSON(requestParameters['bodyCreatePostWithImageTweetCreatePostWithImagePost']),
        };
    }

    /**
     * Create Post With Image
     */
    async createPostWithImageTweetCreatePostWithImagePostRaw(requestParameters: CreatePostWithImageTweetCreatePostWithImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.createPostWithImageTweetCreatePostWithImagePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Create Post With Image
     */
    async createPostWithImageTweetCreatePostWithImagePost(requestParameters: CreatePostWithImageTweetCreatePostWithImagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.createPostWithImageTweetCreatePostWithImagePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePostTweetDeletePostPostIdDelete without sending the request
     */
    async deletePostTweetDeletePostPostIdDeleteRequestOpts(requestParameters: DeletePostTweetDeletePostPostIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling deletePostTweetDeletePostPostIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/delete_post/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Post
     */
    async deletePostTweetDeletePostPostIdDeleteRaw(requestParameters: DeletePostTweetDeletePostPostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.deletePostTweetDeletePostPostIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Delete Post
     */
    async deletePostTweetDeletePostPostIdDelete(requestParameters: DeletePostTweetDeletePostPostIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.deletePostTweetDeletePostPostIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getGoodNumTweetPostsGoodNumPostIdGet without sending the request
     */
    async getGoodNumTweetPostsGoodNumPostIdGetRequestOpts(requestParameters: GetGoodNumTweetPostsGoodNumPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getGoodNumTweetPostsGoodNumPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts/good_num/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Good Num
     */
    async getGoodNumTweetPostsGoodNumPostIdGetRaw(requestParameters: GetGoodNumTweetPostsGoodNumPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.getGoodNumTweetPostsGoodNumPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get Good Num
     */
    async getGoodNumTweetPostsGoodNumPostIdGet(requestParameters: GetGoodNumTweetPostsGoodNumPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getGoodNumTweetPostsGoodNumPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getImagesTweetPostsImagesPostIdGet without sending the request
     */
    async getImagesTweetPostsImagesPostIdGetRequestOpts(requestParameters: GetImagesTweetPostsImagesPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getImagesTweetPostsImagesPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts/images/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Images
     */
    async getImagesTweetPostsImagesPostIdGetRaw(requestParameters: GetImagesTweetPostsImagesPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PostImage>>> {
        const requestOptions = await this.getImagesTweetPostsImagesPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PostImageFromJSON));
    }

    /**
     * Get Images
     */
    async getImagesTweetPostsImagesPostIdGet(requestParameters: GetImagesTweetPostsImagesPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PostImage>> {
        const response = await this.getImagesTweetPostsImagesPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPostsTweetPostsGet without sending the request
     */
    async getPostsTweetPostsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Posts
     */
    async getPostsTweetPostsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetReplyPostModel>>> {
        const requestOptions = await this.getPostsTweetPostsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetReplyPostModelFromJSON));
    }

    /**
     * Get Posts
     */
    async getPostsTweetPostsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetReplyPostModel>> {
        const response = await this.getPostsTweetPostsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReplysTweetPostsReplyPostIdGet without sending the request
     */
    async getReplysTweetPostsReplyPostIdGetRequestOpts(requestParameters: GetReplysTweetPostsReplyPostIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling getReplysTweetPostsReplyPostIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/tweet/posts/reply/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Replys
     */
    async getReplysTweetPostsReplyPostIdGetRaw(requestParameters: GetReplysTweetPostsReplyPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReplyModel>>> {
        const requestOptions = await this.getReplysTweetPostsReplyPostIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReplyModelFromJSON));
    }

    /**
     * Get Replys
     */
    async getReplysTweetPostsReplyPostIdGet(requestParameters: GetReplysTweetPostsReplyPostIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReplyModel>> {
        const response = await this.getReplysTweetPostsReplyPostIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postLikeTweetManegeLikePostIdPost without sending the request
     */
    async postLikeTweetManegeLikePostIdPostRequestOpts(requestParameters: PostLikeTweetManegeLikePostIdPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postId'] == null) {
            throw new runtime.RequiredError(
                'postId',
                'Required parameter "postId" was null or undefined when calling postLikeTweetManegeLikePostIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/manege_like/{post_id}`;
        urlPath = urlPath.replace(`{${"post_id"}}`, encodeURIComponent(String(requestParameters['postId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Post Like
     */
    async postLikeTweetManegeLikePostIdPostRaw(requestParameters: PostLikeTweetManegeLikePostIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.postLikeTweetManegeLikePostIdPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Post Like
     */
    async postLikeTweetManegeLikePostIdPost(requestParameters: PostLikeTweetManegeLikePostIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.postLikeTweetManegeLikePostIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePostTweetUpdatePostPut without sending the request
     */
    async updatePostTweetUpdatePostPutRequestOpts(requestParameters: UpdatePostTweetUpdatePostPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postModel'] == null) {
            throw new runtime.RequiredError(
                'postModel',
                'Required parameter "postModel" was null or undefined when calling updatePostTweetUpdatePostPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2PasswordBearer", []);
        }


        let urlPath = `/tweet/update_post`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PostModelToJSON(requestParameters['postModel']),
        };
    }

    /**
     * Update Post
     */
    async updatePostTweetUpdatePostPutRaw(requestParameters: UpdatePostTweetUpdatePostPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSchema>> {
        const requestOptions = await this.updatePostTweetUpdatePostPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSchemaFromJSON(jsonValue));
    }

    /**
     * Update Post
     */
    async updatePostTweetUpdatePostPut(requestParameters: UpdatePostTweetUpdatePostPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSchema> {
        const response = await this.updatePostTweetUpdatePostPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
