/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddRoomMember
 */
export interface AddRoomMember {
    /**
     * 
     * @type {number}
     * @memberof AddRoomMember
     */
    roomId: number;
    /**
     * 
     * @type {number}
     * @memberof AddRoomMember
     */
    userId: number;
}

/**
 * Check if a given object implements the AddRoomMember interface.
 */
export function instanceOfAddRoomMember(value: object): value is AddRoomMember {
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AddRoomMemberFromJSON(json: any): AddRoomMember {
    return AddRoomMemberFromJSONTyped(json, false);
}

export function AddRoomMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddRoomMember {
    if (json == null) {
        return json;
    }
    return {
        
        'roomId': json['room_id'],
        'userId': json['user_id'],
    };
}

export function AddRoomMemberToJSON(json: any): AddRoomMember {
    return AddRoomMemberToJSONTyped(json, false);
}

export function AddRoomMemberToJSONTyped(value?: AddRoomMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'room_id': value['roomId'],
        'user_id': value['userId'],
    };
}

