/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostImage } from './PostImage';
import {
    PostImageFromJSON,
    PostImageFromJSONTyped,
    PostImageToJSON,
    PostImageToJSONTyped,
} from './PostImage';
import type { CreatePostModel } from './CreatePostModel';
import {
    CreatePostModelFromJSON,
    CreatePostModelFromJSONTyped,
    CreatePostModelToJSON,
    CreatePostModelToJSONTyped,
} from './CreatePostModel';

/**
 * 
 * @export
 * @interface BodyCreatePostWithImageTweetcreatePostWithImagePost
 */
export interface BodyCreatePostWithImageTweetcreatePostWithImagePost {
    /**
     * 
     * @type {Array<PostImage>}
     * @memberof BodyCreatePostWithImageTweetcreatePostWithImagePost
     */
    images: Array<PostImage>;
    /**
     * 
     * @type {CreatePostModel}
     * @memberof BodyCreatePostWithImageTweetcreatePostWithImagePost
     */
    post: CreatePostModel;
}

/**
 * Check if a given object implements the BodyCreatePostWithImageTweetcreatePostWithImagePost interface.
 */
export function instanceOfBodyCreatePostWithImageTweetcreatePostWithImagePost(value: object): value is BodyCreatePostWithImageTweetcreatePostWithImagePost {
    if (!('images' in value) || value['images'] === undefined) return false;
    if (!('post' in value) || value['post'] === undefined) return false;
    return true;
}

export function BodyCreatePostWithImageTweetcreatePostWithImagePostFromJSON(json: any): BodyCreatePostWithImageTweetcreatePostWithImagePost {
    return BodyCreatePostWithImageTweetcreatePostWithImagePostFromJSONTyped(json, false);
}

export function BodyCreatePostWithImageTweetcreatePostWithImagePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreatePostWithImageTweetcreatePostWithImagePost {
    if (json == null) {
        return json;
    }
    return {
        
        'images': ((json['images'] as Array<any>).map(PostImageFromJSON)),
        'post': CreatePostModelFromJSON(json['post']),
    };
}

export function BodyCreatePostWithImageTweetcreatePostWithImagePostToJSON(json: any): BodyCreatePostWithImageTweetcreatePostWithImagePost {
    return BodyCreatePostWithImageTweetcreatePostWithImagePostToJSONTyped(json, false);
}

export function BodyCreatePostWithImageTweetcreatePostWithImagePostToJSONTyped(value?: BodyCreatePostWithImageTweetcreatePostWithImagePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': ((value['images'] as Array<any>).map(PostImageToJSON)),
        'post': CreatePostModelToJSON(value['post']),
    };
}

