/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostImage } from './PostImage';
import {
    PostImageFromJSON,
    PostImageFromJSONTyped,
    PostImageToJSON,
    PostImageToJSONTyped,
} from './PostImage';
import type { CreatePostModel } from './CreatePostModel';
import {
    CreatePostModelFromJSON,
    CreatePostModelFromJSONTyped,
    CreatePostModelToJSON,
    CreatePostModelToJSONTyped,
} from './CreatePostModel';

/**
 * 
 * @export
 * @interface BodyCreatePostWithImageTweetCreatePostWithImagePost
 */
export interface BodyCreatePostWithImageTweetCreatePostWithImagePost {
    /**
     * 
     * @type {CreatePostModel}
     * @memberof BodyCreatePostWithImageTweetCreatePostWithImagePost
     */
    post: CreatePostModel;
    /**
     * 
     * @type {Array<PostImage>}
     * @memberof BodyCreatePostWithImageTweetCreatePostWithImagePost
     */
    images: Array<PostImage>;
}

/**
 * Check if a given object implements the BodyCreatePostWithImageTweetCreatePostWithImagePost interface.
 */
export function instanceOfBodyCreatePostWithImageTweetCreatePostWithImagePost(value: object): value is BodyCreatePostWithImageTweetCreatePostWithImagePost {
    if (!('post' in value) || value['post'] === undefined) return false;
    if (!('images' in value) || value['images'] === undefined) return false;
    return true;
}

export function BodyCreatePostWithImageTweetCreatePostWithImagePostFromJSON(json: any): BodyCreatePostWithImageTweetCreatePostWithImagePost {
    return BodyCreatePostWithImageTweetCreatePostWithImagePostFromJSONTyped(json, false);
}

export function BodyCreatePostWithImageTweetCreatePostWithImagePostFromJSONTyped(json: any, ignoreDiscriminator: boolean): BodyCreatePostWithImageTweetCreatePostWithImagePost {
    if (json == null) {
        return json;
    }
    return {
        
        'post': CreatePostModelFromJSON(json['post']),
        'images': ((json['images'] as Array<any>).map(PostImageFromJSON)),
    };
}

export function BodyCreatePostWithImageTweetCreatePostWithImagePostToJSON(json: any): BodyCreatePostWithImageTweetCreatePostWithImagePost {
    return BodyCreatePostWithImageTweetCreatePostWithImagePostToJSONTyped(json, false);
}

export function BodyCreatePostWithImageTweetCreatePostWithImagePostToJSONTyped(value?: BodyCreatePostWithImageTweetCreatePostWithImagePost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'post': CreatePostModelToJSON(value['post']),
        'images': ((value['images'] as Array<any>).map(PostImageToJSON)),
    };
}

