/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePostModel
 */
export interface CreatePostModel {
    /**
     * 
     * @type {string}
     * @memberof CreatePostModel
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePostModel
     */
    title: string;
}

/**
 * Check if a given object implements the CreatePostModel interface.
 */
export function instanceOfCreatePostModel(value: object): value is CreatePostModel {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreatePostModelFromJSON(json: any): CreatePostModel {
    return CreatePostModelFromJSONTyped(json, false);
}

export function CreatePostModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostModel {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'title': json['title'],
    };
}

export function CreatePostModelToJSON(json: any): CreatePostModel {
    return CreatePostModelToJSONTyped(json, false);
}

export function CreatePostModelToJSONTyped(value?: CreatePostModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'title': value['title'],
    };
}

