/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRoom
 */
export interface CreateRoom {
    /**
     * 
     * @type {string}
     * @memberof CreateRoom
     */
    roomName: string;
    /**
     * 
     * @type {number}
     * @memberof CreateRoom
     */
    user1Id: number;
    /**
     * 
     * @type {number}
     * @memberof CreateRoom
     */
    user2Id: number;
}

/**
 * Check if a given object implements the CreateRoom interface.
 */
export function instanceOfCreateRoom(value: object): value is CreateRoom {
    if (!('roomName' in value) || value['roomName'] === undefined) return false;
    if (!('user1Id' in value) || value['user1Id'] === undefined) return false;
    if (!('user2Id' in value) || value['user2Id'] === undefined) return false;
    return true;
}

export function CreateRoomFromJSON(json: any): CreateRoom {
    return CreateRoomFromJSONTyped(json, false);
}

export function CreateRoomFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRoom {
    if (json == null) {
        return json;
    }
    return {
        
        'roomName': json['room_name'],
        'user1Id': json['user1_id'],
        'user2Id': json['user2_id'],
    };
}

export function CreateRoomToJSON(json: any): CreateRoom {
    return CreateRoomToJSONTyped(json, false);
}

export function CreateRoomToJSONTyped(value?: CreateRoom | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'room_name': value['roomName'],
        'user1_id': value['user1Id'],
        'user2_id': value['user2Id'],
    };
}

