/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMessage
 */
export interface GetMessage {
    /**
     * 
     * @type {number}
     * @memberof GetMessage
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GetMessage
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof GetMessage
     */
    roomId: number;
    /**
     * 
     * @type {number}
     * @memberof GetMessage
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof GetMessage
     */
    userIcon?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetMessage
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the GetMessage interface.
 */
export function instanceOfGetMessage(value: object): value is GetMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function GetMessageFromJSON(json: any): GetMessage {
    return GetMessageFromJSONTyped(json, false);
}

export function GetMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
        'roomId': json['room_id'],
        'userId': json['user_id'],
        'userIcon': json['user_icon'] == null ? undefined : json['user_icon'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function GetMessageToJSON(json: any): GetMessage {
    return GetMessageToJSONTyped(json, false);
}

export function GetMessageToJSONTyped(value?: GetMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
        'room_id': value['roomId'],
        'user_id': value['userId'],
        'user_icon': value['userIcon'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

