/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetReplyPostModel
 */
export interface GetReplyPostModel {
    /**
     * 
     * @type {string}
     * @memberof GetReplyPostModel
     */
    category?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetReplyPostModel
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof GetReplyPostModel
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof GetReplyPostModel
     */
    postId: number;
    /**
     * 
     * @type {string}
     * @memberof GetReplyPostModel
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof GetReplyPostModel
     */
    userIcon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetReplyPostModel
     */
    userName: string;
}

/**
 * Check if a given object implements the GetReplyPostModel interface.
 */
export function instanceOfGetReplyPostModel(value: object): value is GetReplyPostModel {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    return true;
}

export function GetReplyPostModelFromJSON(json: any): GetReplyPostModel {
    return GetReplyPostModelFromJSONTyped(json, false);
}

export function GetReplyPostModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReplyPostModel {
    if (json == null) {
        return json;
    }
    return {
        
        'category': json['category'] == null ? undefined : json['category'],
        'content': json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'postId': json['post_id'],
        'title': json['title'],
        'userIcon': json['user_icon'] == null ? undefined : json['user_icon'],
        'userName': json['user_name'],
    };
}

export function GetReplyPostModelToJSON(json: any): GetReplyPostModel {
    return GetReplyPostModelToJSONTyped(json, false);
}

export function GetReplyPostModelToJSONTyped(value?: GetReplyPostModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'category': value['category'],
        'content': value['content'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'post_id': value['postId'],
        'title': value['title'],
        'user_icon': value['userIcon'],
        'user_name': value['userName'],
    };
}

