/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostModel
 */
export interface PostModel {
    /**
     * 
     * @type {string}
     * @memberof PostModel
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof PostModel
     */
    postId: number;
    /**
     * 
     * @type {string}
     * @memberof PostModel
     */
    title: string;
}

/**
 * Check if a given object implements the PostModel interface.
 */
export function instanceOfPostModel(value: object): value is PostModel {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('postId' in value) || value['postId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function PostModelFromJSON(json: any): PostModel {
    return PostModelFromJSONTyped(json, false);
}

export function PostModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostModel {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'postId': json['post_id'],
        'title': json['title'],
    };
}

export function PostModelToJSON(json: any): PostModel {
    return PostModelToJSONTyped(json, false);
}

export function PostModelToJSONTyped(value?: PostModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'post_id': value['postId'],
        'title': value['title'],
    };
}

