/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImage
 */
export interface PostImage {
    /**
     * 
     * @type {string}
     * @memberof PostImage
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the PostImage interface.
 */
export function instanceOfPostImage(value: object): value is PostImage {
    return true;
}

export function PostImageFromJSON(json: any): PostImage {
    return PostImageFromJSONTyped(json, false);
}

export function PostImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImage {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['image_url'] == null ? undefined : json['image_url'],
    };
}

export function PostImageToJSON(json: any): PostImage {
    return PostImageToJSONTyped(json, false);
}

export function PostImageToJSONTyped(value?: PostImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_url': value['imageUrl'],
    };
}

