/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplyModel
 */
export interface ReplyModel {
    /**
     * 
     * @type {string}
     * @memberof ReplyModel
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof ReplyModel
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ReplyModel
     */
    replyId: number;
    /**
     * 
     * @type {string}
     * @memberof ReplyModel
     */
    userIcon?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReplyModel
     */
    userName: string;
}

/**
 * Check if a given object implements the ReplyModel interface.
 */
export function instanceOfReplyModel(value: object): value is ReplyModel {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('replyId' in value) || value['replyId'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    return true;
}

export function ReplyModelFromJSON(json: any): ReplyModel {
    return ReplyModelFromJSONTyped(json, false);
}

export function ReplyModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplyModel {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'replyId': json['reply_id'],
        'userIcon': json['user_icon'] == null ? undefined : json['user_icon'],
        'userName': json['user_name'],
    };
}

export function ReplyModelToJSON(json: any): ReplyModel {
    return ReplyModelToJSONTyped(json, false);
}

export function ReplyModelToJSONTyped(value?: ReplyModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'reply_id': value['replyId'],
        'user_icon': value['userIcon'],
        'user_name': value['userName'],
    };
}

