/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResponseSchema
 */
export interface ResponseSchema {
    /**
     * API操作の結果を説明するメッセージ
     * @type {string}
     * @memberof ResponseSchema
     */
    message: string;
}

/**
 * Check if a given object implements the ResponseSchema interface.
 */
export function instanceOfResponseSchema(value: object): value is ResponseSchema {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ResponseSchemaFromJSON(json: any): ResponseSchema {
    return ResponseSchemaFromJSONTyped(json, false);
}

export function ResponseSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ResponseSchemaToJSON(json: any): ResponseSchema {
    return ResponseSchemaToJSONTyped(json, false);
}

export function ResponseSchemaToJSONTyped(value?: ResponseSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

