/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomBase
 */
export interface RoomBase {
    /**
     * 
     * @type {Date}
     * @memberof RoomBase
     */
    createdAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof RoomBase
     */
    roomId: number;
    /**
     * 
     * @type {string}
     * @memberof RoomBase
     */
    roomName: string;
}

/**
 * Check if a given object implements the RoomBase interface.
 */
export function instanceOfRoomBase(value: object): value is RoomBase {
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    if (!('roomName' in value) || value['roomName'] === undefined) return false;
    return true;
}

export function RoomBaseFromJSON(json: any): RoomBase {
    return RoomBaseFromJSONTyped(json, false);
}

export function RoomBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomBase {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'roomId': json['room_id'],
        'roomName': json['room_name'],
    };
}

export function RoomBaseToJSON(json: any): RoomBase {
    return RoomBaseToJSONTyped(json, false);
}

export function RoomBaseToJSONTyped(value?: RoomBase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'room_id': value['roomId'],
        'room_name': value['roomName'],
    };
}

