/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitMessage
 */
export interface SubmitMessage {
    /**
     * 
     * @type {string}
     * @memberof SubmitMessage
     */
    content: string;
    /**
     * 
     * @type {number}
     * @memberof SubmitMessage
     */
    roomId: number;
}

/**
 * Check if a given object implements the SubmitMessage interface.
 */
export function instanceOfSubmitMessage(value: object): value is SubmitMessage {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('roomId' in value) || value['roomId'] === undefined) return false;
    return true;
}

export function SubmitMessageFromJSON(json: any): SubmitMessage {
    return SubmitMessageFromJSONTyped(json, false);
}

export function SubmitMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'roomId': json['room_id'],
    };
}

export function SubmitMessageToJSON(json: any): SubmitMessage {
    return SubmitMessageToJSONTyped(json, false);
}

export function SubmitMessageToJSONTyped(value?: SubmitMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'room_id': value['roomId'],
    };
}

