/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMessage
 */
export interface UpdateMessage {
    /**
     * 
     * @type {number}
     * @memberof UpdateMessage
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateMessage
     */
    content: string;
}

/**
 * Check if a given object implements the UpdateMessage interface.
 */
export function instanceOfUpdateMessage(value: object): value is UpdateMessage {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function UpdateMessageFromJSON(json: any): UpdateMessage {
    return UpdateMessageFromJSONTyped(json, false);
}

export function UpdateMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'content': json['content'],
    };
}

export function UpdateMessageToJSON(json: any): UpdateMessage {
    return UpdateMessageToJSONTyped(json, false);
}

export function UpdateMessageToJSONTyped(value?: UpdateMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'content': value['content'],
    };
}

