/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    iconUrl?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    isOnline: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    isVerified: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    status?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    userName: string;
}

/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    if (!('isOnline' in value) || value['isOnline'] === undefined) return false;
    if (!('isVerified' in value) || value['isVerified'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'isOnline': json['is_online'],
        'isVerified': json['is_verified'],
        'status': json['status'] == null ? undefined : json['status'],
        'userId': json['user_id'],
        'userName': json['user_name'],
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'gender': value['gender'],
        'icon_url': value['iconUrl'],
        'is_online': value['isOnline'],
        'is_verified': value['isVerified'],
        'status': value['status'],
        'user_id': value['userId'],
        'user_name': value['userName'],
    };
}

