/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    iconUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreate
     */
    userPass: string;
}

/**
 * Check if a given object implements the UserCreate interface.
 */
export function instanceOfUserCreate(value: object): value is UserCreate {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('userPass' in value) || value['userPass'] === undefined) return false;
    return true;
}

export function UserCreateFromJSON(json: any): UserCreate {
    return UserCreateFromJSONTyped(json, false);
}

export function UserCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['user_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'status': json['status'] == null ? undefined : json['status'],
        'iconUrl': json['icon_url'] == null ? undefined : json['icon_url'],
        'userPass': json['user_pass'],
    };
}

export function UserCreateToJSON(json: any): UserCreate {
    return UserCreateToJSONTyped(json, false);
}

export function UserCreateToJSONTyped(value?: UserCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_name': value['userName'],
        'email': value['email'],
        'gender': value['gender'],
        'status': value['status'],
        'icon_url': value['iconUrl'],
        'user_pass': value['userPass'],
    };
}

